# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.3311, 0.1734, 0.7803, 0.8499, 0.2004, 0.9626, 0.3729],
        [0.0488, 0.0325, 0.4488, 0.4448, 0.0422, 0.1982, 0.3761],
        [0.3053, 0.6757, 0.2540, 0.8480, 0.2246, 0.1890, 0.0458],
        [0.4766, 0.0512, 0.9971, 0.5634, 0.5375, 0.5503, 0.8221],
        [0.4960, 0.6316, 0.9859, 0.0917, 0.7832, 0.3633, 0.0622],
        [0.9762, 0.9001, 0.4883, 0.2951, 0.2235, 0.4284, 0.6809],
        [0.6726, 0.8214, 0.1760, 0.1233, 0.1448, 0.4608, 0.2912]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
vector_tensor = torch.rand(1, 7)
print(vector_tensor)

# Perform matrix multiplication
# vector_tensor.T @ tensor # This will throw an error because of the shape of the tensors

vector_tensor @ tensor


tensor([[0.9053, 0.0854, 0.1122, 0.3667, 0.2271, 0.1111, 0.0488]])


tensor([[0.7668, 0.5377, 1.4255, 1.1688, 0.6170, 1.2639, 0.7802]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
tensor = torch.rand(7, 7)
vector_tensor = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(tensor, vector_tensor.T)
#vector_tensor @ tensor.T


tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print("Cuda available? ", torch.cuda.is_available())

# Create two random tensors on GPU
tensor = torch.rand(7, 7).to('cuda')
vector_tensor = torch.rand(1, 7).to('cuda')


Cuda available?  True



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor, vector_tensor.T)
#vector_tensor @ tensor.T
result

tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max = torch.max(result)
print(max)

# Find min
min = torch.min(result)
print(min)


tensor(3.1874, device='cuda:0')
tensor(1.5166, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
max_index = torch.argmax(result) 
print(max_index)

# Find arg min
min_index = torch.argmin(result)
print(min_index)


tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)


# Create random tensor
first = torch.rand(1, 1, 1, 10)
# Remove single dimensions
second = torch.squeeze(first)

# Print out tensors and their shapes
print(first, first.shape)
print(second, first.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([1, 1, 1, 10])
