# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
%pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.6/766.6 MB 6.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 11.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 20.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 14.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 4.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 7.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 15.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 24.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 17.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 12.3 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 14.3 MB/s eta 0:00:0000:0100:01
   ━━━━

In [5]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

/home/mateusw/jupyter_lab/jupyter_env/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor([[0.8249, 0.7111, 0.5275, 0.2261, 0.8133, 0.2317, 0.9354],
        [0.7120, 0.0741, 0.0775, 0.1363, 0.3923, 0.6914, 0.8208],
        [0.0464, 0.7767, 0.8738, 0.8784, 0.6939, 0.7249, 0.3275],
        [0.9103, 0.4073, 0.0883, 0.3778, 0.0218, 0.0554, 0.9043],
        [0.8804, 0.3433, 0.1429, 0.8535, 0.5081, 0.3712, 0.1853],
        [0.8325, 0.3516, 0.7047, 0.8334, 0.5806, 0.3805, 0.7714],
        [0.1559, 0.5788, 0.2799, 0.0555, 0.7039, 0.4962, 0.2316]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [16]:
# Create another random tensor
vector_tensor = torch.rand(1, 7)
print(vector_tensor)

# Perform matrix multiplication
# vector_tensor.T @ tensor # This will throw an error because of the shape of the tensors

vector_tensor @ tensor


tensor([[0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])


tensor([[2.7829, 2.3616, 2.4559, 2.2417, 1.6757, 2.4328, 1.4800]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
tensor = torch.rand(7, 7)
vector_tensor = torch.rand(7, 1)

# Matrix multiply tensors
vector_tensor.T @ tensor


tensor([[1.9765, 1.3968, 2.4503, 1.0051, 1.7770, 1.7122, 1.2340]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print("Cuda available? ", torch.cuda.is_available())

# Create two random tensors on GPU


Cuda available?  False



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
